#  menu items
[[main]]
  name = "🏃 Get started"
  weight = 1
  url = "book/get_started/"

[[main]]
  name = "📖 Book"
  weight = 2
  url = "book/"

[[main]]
  name = "📚 Documentation"
  weight = 3
  url = "documentation/"

[[main]]
  name = "ℹ️ About"
  weight = 4
  url = "about/"